### ISSUE TITLE
Source for live image to ascii

### ISSUE THREAD

**Issue by GrosSacASac** [symisc/ascii_art#1]
Where can I find the source for https://art.pixlab.io/#render_cam ?: the code that that produces ascii output with video input. 

Is it done client side ?

**Comment by symisc** [comment]
Yes, it is done on the client side using the exported ASCII Art API: **AsciiArtInit**(), **AsciiArtRender**() and so forth. Video Frames are obtained through the getUserMedia() interfaces, converted to grayscale and then processed. 
All of this require the trained model that perform the rendering and is to be downloaded from http://pixlab.io/art
