### ISSUE TITLE
How to compile this project? undefined reference to `AsciiArtLoadImage'

### ISSUE THREAD

**Issue by akashdexati** [symisc/ascii_art#2]
I am getting below error when compiling with cmake
**CMakeFiles/test.dir/sample.c.o: In function `main':
sample.c:(.text+0x7b): undefined reference to `AsciiArtLoadImage'**

Below command is also giving same error
**gcc -W -Wall -O6 -o ascii_test sample.c ascii_art.c stb_image.h**

**Comment by symisc** [comment]
Could you paste your CMakefile.txt build script?

**Comment by akashdexati** [comment]
**CMakeLists.txt**
cmake_minimum_required(VERSION 2.8.12)
set(SOURCES ascii_art.c ascii_art.h stb_image.h sample.c)
add_executable(test ${SOURCES})

**Run commands in sequence**
cmake .
make

**Comment by symisc** [comment]
The following macro **ART_ENABLE_STB_IMAGE** have to be defined during compile time: . Your command line build should look like:
gcc -W -Wall -O6 ascii_art.c sample.c -o ascii -D **ART_ENABLE_STB_IMAGE**

**Comment by akashdexati** [comment]
Thanks.
Adding an -lm in the end worked for me.
gcc -W -Wall -O6 ascii_art.c sample.c -o ascii -D ART_ENABLE_STB_IMAGE **-lm**

Also can you tell me if it is possible to use this code with Android JNI ?

**Comment by symisc** [comment]
The code is ANSI-C so it should compile fine without problem on most platform with a C compiler.

**Comment by akashdexati** [comment]
I am getting **segmentation fault** for every image. Even a small image is not getting processed. 
Do we have any constraint on image size ?

**Comment by akashdexati** [comment]
@symisc 
I am testing the code with clang++ compiler. It does initial compilation but fails at linking 

**error: undefined reference to 'AsciiArtLoadImage'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)**

Can you tell the right way to compile this ?
