### ISSUE TITLE
How to create a png output file as shown in the demo image

### ISSUE THREAD

**Issue by akashdexati** [symisc/ascii_art#3]
The image at URL has middle image in png format
https://camo.githubusercontent.com/65164475128f734e471dd21552dbc9b2e65f14f7/68747470733a2f2f692e696d6775722e636f6d2f63644a427a58492e706e67

I am able to save the generated ascii characters in  **'.txt'** file. How to create a **png** file for the same ? Is there any existing code for the same ?

**Comment by symisc** [comment]
Check the [SOD project](https://sod.pixlab.io) for saving PNG/JPEG images to disk or contact PixLab for professional paid support.
